### ISSUE TITLE
Error when running on bun

### ISSUE THREAD

**Issue by sparty02** [lukeed/fetch-event-stream#5]
Bun (as of 1.1.6) doesn't implement TextDecoderStream, so it throws with `Can't find variable: TextDecoderStream`

**Comment by lukeed** [comment]
Not sure how you’re installing. This package injects a polyfill before npm publish. Automated via dnt

**Comment by lukeed** [comment]
Oh sorry, thought you were talking about `TextLineStream`

You can find a global polyfill for `TextDecoderStream`, but there's nothing I can/will do for bun here since that's just a core Web API that they need to implemented. But instead theyre too busy modifying existing standard APIs instead of adding support for existing ones.

**Comment by Milkshiift** [comment]
I am probably missing something, but why can't a polyfill be used? This one for example https://github.com/oven-sh/bun/issues/5648#issuecomment-2143413569
Doesn't look like a native implementation is coming soon

**Comment by lukeed** [comment]
One can, but you have to bring/supply it. The one you linked may work.

```js
globalThis.TextDecoderStream ||= TextDecoderStream;
```
